### ISSUE TITLE
optimize_guides output updates

### ISSUE THREAD

**Issue by emilydc** [czbiohub/guide_design_tools#13]
Feature request: The output of optimize_guides currently has the total number of reads in the header line, and the number of reads and cumulative number of reads in columns. It would be great if there was an additional column that was cumulative fraction of reads - just the cumulative number of reads column divided by the total number of reads. That's what you always want to plot in the elbow graph to tell how DASHable the sample is.

Also, I think the "Site index" column should be removed. I don't know of anything that it's useful for, and I find it distracting when I'm looking at the file.

**Comment by alyden** [comment]
Additionally, if we could add a guide index column, I think that would be helpful for referencing guides downstream. Just a number 1-whatever in the order that they appear in optimize_guides. I always end up adding this column to elbow plot in excel anyway and to look at individual guides
